#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

latest_release_tag="${RELEASE_TAG:-runtime-latest}"
versioned_release_tag="${VERSIONED_RELEASE_TAG:-runtime-$(date -u +%Y%m%d-%H%M%S)}"
asset_dir="${ASSET_DIR:-$DIST_DIR}"
overwrite="${OVERWRITE:-true}"
body_file="$WORK_DIR/release-body.md"
manifest_file="$asset_dir/native-downloads.json"

need_cmd gh
need_cmd python3

mapfile -t assets < <(find "$asset_dir" -type f -name '*.zip' | sort)
[[ "${#assets[@]}" -gt 0 ]] || die "no zip assets found under $asset_dir"

generate_native_downloads_manifest() {
  local out="$1"
  local url_release_tag="$2"
  shift 2

  local repo="${GITHUB_REPOSITORY:-squi2rel/VideoPlayer-Library}"
  python3 - "$repo" "$url_release_tag" "$out" "$@" <<'PY'
import hashlib
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote

repo, url_release_tag, out, *assets = sys.argv[1:]
data = {"urls": {"vlc": {}, "mpv": {}}}
pattern = re.compile(r"^lib(vlc|mpv)-([^-]+)-(.+)\.zip$")

for asset in sorted(assets, key=lambda p: Path(p).name):
    path = Path(asset)
    match = pattern.fullmatch(path.name)
    if not match:
        continue

    runtime, platform, arch = match.groups()
    key = f"{platform}_{arch}"
    sha256 = hashlib.sha256(path.read_bytes()).hexdigest()
    url = (
        f"https://github.com/{repo}/releases/download/"
        f"{quote(url_release_tag, safe='')}/{quote(path.name)}"
    )
    data["urls"][runtime][key] = [{"url": url, "sha256": sha256}]

Path(out).write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
PY
}

publish_to_release() {
  local tag="$1"

  if gh release view "$tag" >/dev/null 2>&1; then
    gh release edit "$tag" --notes-file "$body_file"
  else
    gh release create "$tag" --title "$tag" --notes-file "$body_file"
  fi

  if [[ "$overwrite" == "true" ]]; then
    gh release upload "$tag" "${upload_assets[@]}" --clobber
  else
    gh release upload "$tag" "${upload_assets[@]}"
  fi
}

generate_native_downloads_manifest "$manifest_file" "$versioned_release_tag" "${assets[@]}"
upload_assets=("${assets[@]}" "$manifest_file")

{
  echo "# Runtime Libraries"
  echo
  echo "Generated by GitHub Actions from stable release sources."
  echo
  echo "Versioned release: \`$versioned_release_tag\`"
  echo "Moving release: \`$latest_release_tag\`"
  echo
  echo "\`native-downloads.json\` URLs point to the versioned release so old manifests keep matching their recorded hashes."
  echo
  echo "| Asset | SHA256 |"
  echo "| --- | --- |"
  for asset in "${assets[@]}"; do
    echo "| $(basename "$asset") | $(sha256_file "$asset") |"
  done
} >"$body_file"

log "publish runtime assets to versioned release $versioned_release_tag"
publish_to_release "$versioned_release_tag"

if [[ "$latest_release_tag" != "$versioned_release_tag" ]]; then
  log "publish runtime assets to moving release $latest_release_tag"
  publish_to_release "$latest_release_tag"
fi
