#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

release_tag="${RELEASE_TAG:?RELEASE_TAG is required}"
asset_dir="${ASSET_DIR:-$DIST_DIR}"
overwrite="${OVERWRITE:-true}"
body_file="$WORK_DIR/release-body.md"

need_cmd gh

mapfile -t assets < <(find "$asset_dir" -type f -name '*.zip' | sort)
[[ "${#assets[@]}" -gt 0 ]] || die "no zip assets found under $asset_dir"

{
  echo "# Runtime Libraries"
  echo
  echo "Generated by GitHub Actions from stable release sources."
  echo
  echo "| Asset | SHA256 |"
  echo "| --- | --- |"
  for asset in "${assets[@]}"; do
    echo "| $(basename "$asset") | $(sha256_file "$asset") |"
  done
} >"$body_file"

if gh release view "$release_tag" >/dev/null 2>&1; then
  gh release edit "$release_tag" --notes-file "$body_file"
else
  gh release create "$release_tag" --title "$release_tag" --notes-file "$body_file"
fi

if [[ "$overwrite" == "true" ]]; then
  gh release upload "$release_tag" "${assets[@]}" --clobber
else
  gh release upload "$release_tag" "${assets[@]}"
fi
